export const allProducts = [
  {
    prodName: 'Shoes',
    prodImg: 'Some image',
    prodDesc: 'Very good',
    prodCost: '$49.99',
    numInCart: 0,
    id: 1,
  },
  {
    prodName: 'Shirt',
    prodImg: 'Some image',
    prodDesc: 'Quality fabric',
    prodCost: '$19.99',
    numInCart: 0,
    id: 2,
  },
  {
    prodName: 'Pants',
    prodImg: 'Some image',
    prodDesc: 'Cotton',
    prodCost: '$39.99',
    numInCart: 0,
    id: 3,
  },
  {
    prodName: 'Sunglasses',
    prodImg: 'Some image',
    prodDesc: 'Polarized',
    prodCost: '$49.99',
    numInCart: 0,
    id: 4,
  },
  {
    prodName: 'Shoes',
    prodImg: 'Some image',
    prodDesc: 'Very good',
    prodCost: '$49.99',
    numInCart: 0,
    id: 5,
  },
  {
    prodName: 'Shirt',
    prodImg: 'Some image',
    prodDesc: 'Quality fabric',
    prodCost: '$19.99',
    numInCart: 0,
    id: 6,
  },
  {
    prodName: 'Pants',
    prodImg: 'Some image',
    prodDesc: 'Cotton',
    prodCost: '$39.99',
    numInCart: 0,
    id: 7,
  },
  {
    prodName: 'Sunglasses',
    prodImg: 'Some image',
    prodDesc: 'Polarized',
    prodCost: '$49.99',
    numInCart: 0,
    id: 8,
  },
];